### ISSUE TITLE
Volumes still rather slow

### ISSUE THREAD

**Issue by BastianHofmann** [adlogix/docker-machine-nfs#58]
I'm running a rails application in a container with the root directory as a volume.

Excerpt from docker-compose.yml:

```
app:
    image: "some/image:tag"
    command: "bundle exec rails s -b 0.0.0.0"
    volumes:
        - "./:/var/www"
    links:
        - db
        - redis
    ports:
        - "80:3000"
    environment:
        - ...
```

When I use the standard virtual box sharing, it takes about 10 seconds to load a single page. With docker-machine-nfs it takes about 2 seconds. I also tried https://github.com/brikis98/docker-osx-dev, which uses rsync. With docker-osx-dev a page load takes about 200ms.

Is this performance hit realistic or did I do something wrong?

PS: I would use docker-osx-dev, but unfortunately the rsync sharing works only in one direction...
